#!/usr/bin/env bash

##### START MOULE CONFIGURATION KEYVALUES #####
##### END MOULE CONFIGURATION KEYVALUES #####
#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="schema_registry.local"
export SOLECO_MODULE_VERSION=""
##### START COMPONENT CONFIGURATION #####
