##### BEGIN soleco/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END soleco/Dockerfile/image-header #####

##### BEGIN soleco/Dockerfile/conteco #####
COPY ./soleco/ /soleco/
RUN rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END soleco/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN soleco/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="soleco" \
    CONTECO_TYPE="kz_ksql_ekg" \
    CONTECO_NAME="poc" \
    CONTECO_TAG="v1.0.1" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="soleco"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="soleco" \
      io.vcweb.type="kz_ksql_ekg" \
      io.vcweb.name="poc" \
      io.vcweb.tag="v1.0.1" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="soleco" \
      io.vcweb.label="kz_ksql_ekg.poc -SolEco" \
      io.vcweb.description="The SolEco Kafka KSQL ElasticSearch POC solution." \
      io.vcweb.docker.cmd.help="docker run vcwebio/soleco.kz_ksql_ekg.poc --help"
##### END soleco/Dockerfile/env-labels-footer #####
