#!/usr/bin/env bash

export CONTECO_LABEL="kz_ksql_ekg.poc -SolEco"
export CONTECO_DESCRIPTION="The SolEco Kafka KSQL ElasticSearch POC solution."

export CONTECO_TYPE="kz_ksql_ekg"
export CONTECO_NAME="poc"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="soleco"
