- type: http
  id: external_kafka_connect_endpoint
  name: Kafka Connect External
  hosts: ["http://:"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "kz_ksql_ekg_poc/platform/connect"
    stack: kafka_connect
    type: external
    service: kafka_connect
    area: endpoint




- type: http
  id: internal_kafka_connect_endpoint
  name: Kafka Connect Internal
  hosts: ["http://kz_ksql_ekg_poc_platform_connect_kafka_rest_kafka_rest:8083"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "kz_ksql_ekg_poc/platform/connect"
    stack: kafka_connect
    type: internal
    service: kafka_connect
    area: endpoint
