- type: http
  id: external_ksql_ksql_server_endpoint
  name: KSQL Server External
  hosts: ["http://${CONTECO_HOSTNAME}:"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "ksqldb_local"
    stack: ksql
    type: external
    service: ksql_server
    area: endpoint




- type: http
  id: internal_ksql_ksql_server_endpoint
  name: KSQL Server Internal
  hosts: ["http://module_ksqldb_local_ksql_ksql_server:8088"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "ksqldb_local"
    stack: ksql
    type: internal
    service: ksql_server
    area: endpoint
