#!/usr/bin/env bash



executionplane --silent docker container prune --force

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_streamsets_metrics_monitor_heartbeat_data_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_streamsets_metrics_monitor_heartbeat_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_streamsets_metrics_monitor_heartbeat_monitors_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_streamsets_metrics_monitor_heartbeat_monitors_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_streamsets_streamsets_streamsets_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_streamsets_streamsets_streamsets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
