#!/usr/bin/env bash

##### START MOULE CONFIGURATION KEYVALUES #####
##### END MOULE CONFIGURATION KEYVALUES #####
#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="kafka_connect.local"
export SOLECO_MODULE_VERSION=""
##### END COMPONENT CONFIGURATION #####
