#!/usr/bin/env bash


	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_kafka_connect_kafka_connect_secrets_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_kafka_connect_kafka_connect_connect_secrets_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_kafka_connect_kafka_connect_data_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_kafka_connect_kafka_connect_jars_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_connect_metrics_monitor_heartbeat_monitors_volume
	
executionplane --silent docker run -v kz_ksql_ekg_poc_platform_connect_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/platform/connect/_component/_volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
