#!/usr/bin/env bash


	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ekg_ekg_elasticsearch_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ekg_ekg_grafana_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ekg_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ekg_metrics_monitor_heartbeat_monitors_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ekg_metrics_overlay_metrics_overlay_volume
	
executionplane --silent docker run -v kz_ksql_ekg_poc_platform_ekg_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/platform/ekg/_component/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
