---
version: '3'
services:

# START SERVICE ksqldb_server.base
  ksql_server:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksqldb_server.base:0.9.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${KSQL_KSQL_BOOTSTRAP_SERVERS}','KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true','KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true','KSQL_KSQL_SERVICE_ID=${KSQL_KSQL_KSQL_SERVICE_ID}'${KSQL_MODE}]
    command: []
    volumes: []
    ports: [${KSQL_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${KSQL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${KSQL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${KSQL_COMPOSE_EXTENSIONS}
# END SERVICE ksqldb_server.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
