#!/usr/bin/env bash



executionplane --silent docker container prune --force

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_kz_kafka_secrets_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_kz_kafka_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_kz_kafka_data_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_kz_kafka_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_secrets_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_data_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_log_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_kz_zookeeper_log_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_metrics_monitor_heartbeat_data_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_metrics_monitor_heartbeat_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_metrics_monitor_heartbeat_monitors_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_metrics_monitor_heartbeat_monitors_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "kz_ksql_ekg_poc_platform_kz_metrics_overlay_metrics_overlay_volume"
	result=$(docker volume ls | grep "kz_ksql_ekg_poc_platform_kz_metrics_overlay_metrics_overlay_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
