---
version: '3'
services:

# START SERVICE ksql_server.base
  ksql_server:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksql_server.base:5.4.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${KSQL_KSQL_BOOTSTRAP_SERVERS}','KSQL_KSQL_SERVICE_ID=${KSQL_KSQL_KSQL_SERVICE_ID}'${KSQL_MODE}]
    command: []
    volumes: [${CONTECO_STACKPREFIX}_ksql_server_volume:/conteco/pwd]
    ports: [${KSQL_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${KSQL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${KSQL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${KSQL_COMPOSE_EXTENSIONS}
# END SERVICE ksql_server.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_ksql_server_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
