- type: http
  id: external_ksql_ksql_server_endpoint
  name: KSQL Server External
  hosts: ["http://:"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "kz_ksql_ekg_poc/platform/ksql"
    stack: ksql
    type: external
    service: ksql_server
    area: endpoint




- type: http
  id: internal_ksql_ksql_server_endpoint
  name: KSQL Server Internal
  hosts: ["http://kz_ksql_ekg_poc_platform_ksql_ksql_ksql_server:8088"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "kz_ksql_ekg_poc/platform/ksql"
    stack: ksql
    type: internal
    service: ksql_server
    area: endpoint
