#!/usr/bin/env bash


	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ksqldb_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create kz_ksql_ekg_poc_platform_ksqldb_metrics_monitor_heartbeat_monitors_volume
	
executionplane --silent docker run -v kz_ksql_ekg_poc_platform_ksqldb_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/platform/ksqldb/_component/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
